### Teste do endpoint GET para listar livros
GET http://localhost:3000/livros
Content-Type: application/json

### Teste do endpoint POST para adicionar um livro
POST http://localhost:3000/livros
Content-Type: application/json

{   "ïd":1,
    "titulo": "O Poderoso Chefão",
    "autor": "Mario Puzzo",
    "ano_publicacao": 1969,
    "genero": "Drama" 
    //Adicionando um livro
}

### Teste com dados incompletos para verificar validação
POST http://localhost:3000/livros

{   
    "ïd":2,
    "titulo": "O Senhor dos Anéis",
    "autor": "J.R.R. Tolkien",
   //Faltam os campos Ano de publicação e genero
}